ALTER TABLE BOOK
	DROP CONSTRAINT Fk_Book_PublisherId;

ALTER TABLE PUBLISHER
	DROP CONSTRAINT Pk_PublisherId;

ALTER TABLE PUBLISHER
	DROP COLUMN PublisherId;

ALTER TABLE BOOK
	DROP COLUMN PublisherId;

ALTER TABLE PUBLISHER
	ADD [Name] VARCHAR(200) NOT NULL;

ALTER TABLE PUBLISHER
	ADD CONSTRAINT Pk_PublisherName PRIMARY KEY ([Name]);

ALTER TABLE BOOK
	ADD PublisherName VARCHAR(200) NOT NULL;

ALTER TABLE BOOK
	ADD CONSTRAINT Fk_Book_PublisherName FOREIGN KEY (PublisherName)
	REFERENCES PUBLISHER ([Name]);