ALTER TABLE BOOK_LOANS
	DROP CONSTRAINT Fk_BookLoans_CardNo;

ALTER TABLE BOOK_LOANS
	DROP CONSTRAINT Fk_BookLoans_BranchId;

ALTER TABLE BOOK_LOANS
	DROP CONSTRAINT Fk_BookLoans_BookId;

ALTER TABLE BOOK_COPIES
	DROP CONSTRAINT Fk_BookCopies_BookId;

ALTER TABLE BOOK_COPIES
	DROP CONSTRAINT Fk_BookCopies_BranchId;

DROP TABLE BORROWER;
DROP TABLE BOOK_LOANS;
DROP TABLE BOOK_COPIES;
DROP TABLE LIBRARY_BRANCH;