ALTER TABLE BOOK
	DROP CONSTRAINT Fk_Book_PublisherName;

ALTER TABLE PUBLISHER
	DROP CONSTRAINT Pk_PublisherName

ALTER TABLE PUBLISHER
	DROP COLUMN [Name];

ALTER TABLE BOOK
	DROP COLUMN PublisherName;

ALTER TABLE PUBLISHER
	ADD PublisherId INT NOT NULL;

ALTER TABLE PUBLISHER
	ADD CONSTRAINT Pk_PublisherId PRIMARY KEY (PublisherId);

ALTER TABLE BOOK
	ADD PublisherId INT NOT NULL;

ALTER TABLE BOOK
	ADD CONSTRAINT Fk_Book_PublisherId FOREIGN KEY (PublisherId) REFERENCES PUBLISHER (PublisherId);