CREATE TABLE LIBRARY_BRANCH (
	BranchId INT PRIMARY KEY,
	BranchName VARCHAR(200) NOT NULL,
	[Address] VARCHAR(400)
);

CREATE TABLE BORROWER (
	CardNo INT PRIMARY KEY,
	[Name] VARCHAR(200) NOT NULL,
	[Address] VARCHAR(400),
	Phone DECIMAL(20)
);

CREATE TABLE BOOK_COPIES (
	BookId INT NOT NULL,
	BranchId INT NOT NULL,
	No_Of_Copies INT DEFAULT 1,
	PRIMARY KEY (BookId, BranchId),
	CONSTRAINT Fk_BookCopies_BookId FOREIGN KEY (BookId) REFERENCES BOOK (BookId),
	CONSTRAINT Fk_BookCopies_BranchId FOREIGN KEY (BranchId) REFERENCES LIBRARY_BRANCH(BranchId)
);

CREATE TABLE BOOK_LOANS (
	BookId INT NOT NULL,
	BranchId INT NOT NULL,
	CardNo INT NOT NULL,
	DateOut DATE,
	DueDate DATE,
	PRIMARY KEY (BookId, BranchId, CardNo),
	CONSTRAINT Fk_BookLoans_BookId FOREIGN KEY (BookId) REFERENCES BOOK(BookId),
	CONSTRAINT Fk_BookLoans_BranchId FOREIGN KEY (BranchId) REFERENCES LIBRARY_BRANCH(BranchId),
	CONSTRAINT Fk_BookLoans_CardNo FOREIGN KEY (CardNo) REFERENCES BORROWER(CardNo)
);